services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: blogdb  # Add this line
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"